keptn-contrib/job-executor-service

- helm/templates/configmap.yaml
- helm/values.schema.json
- helm/values.yaml
* Define initcontainer values from `configmap` in `values.yaml`
* Extend pattern of image property to allow repositories starting with numbers and longer names (aws ecr)
> Define initcontainer image values used in configmap in values.yaml

- README.md
- cmd/job-executor-service/main.go
- deploy/service.yaml
- helm/templates/configmap.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/eventhandler/eventhandler_test.go
- pkg/eventhandler/eventhandlers.go
- pkg/k8sutils/connect.go
- pkg/k8sutils/fake/connect_mock.go
- pkg/k8sutils/job.go
- pkg/k8sutils/resourcerequirements.go
- pkg/k8sutils/resourcerequirements_test.go
Service:
```yaml
limits:
cpu: 1
memory: 512Mi
requests:
cpu: 50m
memory: 128Mi
```
Distributor:
```yaml
requests:
memory: "32Mi"
cpu: "50m"
limits:
memory: "128Mi"
cpu: "500m"
```
The `initcontainer` and the `job` container will use the default resource quotas defined as environment variables. They
can be set in [`deploy/service.yaml`](deploy/service.yaml):
```yaml
- name: DEFAULT_RESOURCE_LIMITS_CPU
value: "1"
- name: DEFAULT_RESOURCE_LIMITS_MEMORY
value: "512Mi"
- name: DEFAULT_RESOURCE_REQUESTS_CPU
value: "50m"
- name: DEFAULT_RESOURCE_REQUESTS_MEMORY
value: "128Mi"
```
or for helm in [`helm/templates/configmap.yaml`](helm/templates/configmap.yaml):
```yaml
default_resource_limits_cpu: "1"
default_resource_limits_memory: "512Mi"
default_resource_requests_cpu: "50m" …
```
> Configurable resource quotas

- deploy/service.yaml
In Keptn 0.8.4, the distributor will be extended with the functionality of registering itself as a Keptn uniform integration at the Keptn's Uniform API.
To enable this feature, the following changes need to be made:
First, the image of the `distributor` container of the deployment needs to be set to `keptn/distributor:0.8.4`:
```
- name: distributor
image: keptn/distributor:0.8.4
```
Second, the following environment variables have to be added to the `distributor` container:
```
- name: VERSION
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
- name: K8S_DEPLOYMENT_NAME
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
- name: K8S_POD_NAME
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: metadata.name …
```
> added configuration for uniform registration feature of distributor

- helm/templates/deployment.yaml
- helm/values.yaml
The distributor references the following fields from labels, but they are not present.
```yaml
- name: VERSION
valueFrom:
fieldRef:
fieldPath: metadata.labels['app.kubernetes.io/version']
- name: K8S_DEPLOYMENT_NAME
valueFrom:
fieldRef:
fieldPath: metadata.labels['app.kubernetes.io/name']
```
Switch the labels from `selectorLabels` to `labels` which includes the missing labels.
> fix labels referenced by distributor env vars

- README.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/eventhandler/eventhandlers.go
- pkg/file/file_test.go
- pkg/k8sutils/job.go
- releasenotes/releasenotes_V0.1.2.md
- test-data/config.yaml
With the current way it is not really possible to write more complex commands, since everything gets just splitted by white spaces and added as command to the k8s job, which can lead to issues with chained commands `&&`. Let users decide how exactly they want to split commands and also allow definition of args, passed through to the k8s job.
Current declaration:
```yaml
cmd: "locust --config /keptn/locust/locust.conf -f /keptn/locust/basic.py --host $(HOST)"
```
New declaration:
```yaml
cmd:
- locust
args:
- '--config'
- /keptn/locust/locust.conf
- '-f'
- /keptn/locust/basic.py
- '--host'
- $(HOST)
```
Bumped config version to `v2` because it is not backwards compatible.
> Extend command to allow declaration of arrays and and args to be passed through to the k8s job

- README.md
- pkg/k8sutils/job.go
- pkg/k8sutils/job_test.go
There is now a new env variable source `string` which allows you to
specify the value of an env var, by providing the `value` property.
This fixes #34
> Add new env variable source `string`

- .github/workflows/CI.yml
- .github/workflows/Release.yml
- .gitignore
- lint/Makefile
- lint/main.go
- test-data/config.yaml
* Add github actions for building respective binaries after new release creation and adds them as assets (not fully tested but let's see what happens on the next release :bomb:)
> Add simple cli tool that parses a given job config

- README.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/eventhandler/eventhandler_test.go
- pkg/eventhandler/eventhandlers.go
- pkg/k8sutils/connect.go
- pkg/k8sutils/fake/connect_mock.go
- pkg/k8sutils/job.go
The default settings allow a job to run for 5 min until the job executor service cancels the task execution. The default
value can be overwritten for each task and is declared as seconds. The setting below would result in a poll duration of
20 minutes for this specific task:
```yaml
tasks:
- name: "Run locust smoke tests"
...
maxPollDuration: 1200
```
Internally we use 5 seconds between each poll attempt. So the above setting would result in 240 poll attempts.
> Make poll duration for single tasks configureable

- README.md
The `workingDirectory` parameter mentioned in the `README.md` file does not match the `workingDir` name defined in the [code](https://github.com/keptn-sandbox/job-executor-service/blob/main/pkg/config/config.go#L48) and therefore throws an error when used:
```
2021/07/20 15:11:48 Could not parse config: yaml: unmarshal errors: line 19: field workingDirectory not found in type config.Task
```
> Fix workdir documentation

- README.md
- pkg/config/config.go
- pkg/eventhandler/eventhandlers.go
- pkg/k8sutils/job.go
Allowing the user to specify `JSON` and `YAML` as formats for the environment event data. 
```
- name: EVENT
value: "$"
valueFrom: event
as: json
```
If the `as` field is left empty the event will either be passed as JSON if it is a map or as a string if it is a single value.
```
- name: EVENT
value: "$"
valueFrom: event
```
#59
> Event data formatting

- README.md
- pkg/eventhandler/eventhandler_test.go
- pkg/eventhandler/eventhandlers.go
- test-events/action.triggered.json
- test-events/test.triggered.json
This commit extends the job ececutor service to send back the start and
end event metadata on test.finished events.
Still TODO:
* Add tests
* Start a discussion if this behaviour should be added for more shipyard tasks beside `test` tasks.
> feat: Add start and end event metadata for test finished events

- helm/README.md
Remote control plane is enabled by default in the values.yaml.
Update readme to fix this descrepancy
> Control Plane Enabled: Readme

- .ci_env
- Makefile
- README.md
- cmd/job-executor-service-initcontainer/main.go
- cmd/job-executor-service-lint/main.go
- cmd/job-executor-service/main.go
- deploy/service.yaml
- go.mod
- helm/README.md
- helm/values.yaml
- pkg/eventhandler/eventhandler_test.go
- pkg/eventhandler/eventhandlers.go
- pkg/file/file.go
- pkg/file/file_test.go
- pkg/k8sutils/connect.go
- pkg/k8sutils/fake/connect_mock.go
- pkg/k8sutils/job.go
- pkg/k8sutils/job_test.go
- pkg/keptn/config_service_test.go
- scripts/build-push-deploy-ks3.sh
- skaffold.yaml
moves all relevant part of this repo from keptn-sandbox to keptn-contrib (including the DockerHub organization used).
#93
> Move from keptn-sandbox to keptn-contrib

- pkg/config/config.go
- pkg/k8sutils/job.go
Implements the` TTLSecondsAfterFinished` parameter to cleanup Jobs after they have reached the `Completed` status.
```
apiVersion: v2
actions:
- name: "Print files"
events:
- name: "sh.keptn.event.sample.triggered"
tasks:
- name: "Show files in bin"
image: "alpine"
workingDir: "/bin"
cmd:
- ls
ttlSecondsAfterFinished: 60
``` 
#44
> feat: Add support for ttlSecondsAfterFinished (#44)

- Dockerfile
- deploy/service.yaml
- go.mod
- go.sum
- helm/values.yaml
- initcontainer.Dockerfile
- upgrades go-utils to 0.10.0
- upgrades keptn/distributor to 0.10.0
- upgrades alpine from 3.11 to 3.15 in both Dockerfiles
Fixes #106 
Proof:
> feat(core): upgrade to keptn 0.10.0 (#106)

- .github/workflows/pre-release.yml
- .github/workflows/validate-semantic-pr.yml
- .versionrc.json
- Fixes the versioning schema used for (pre-)releases by adding a .versionrc file
- Uses the latest released version of keptn/gh-automation workflows
- adds `lint` and `initcontainer` as valid contexts for semantic commit messages
> build: fix pre-release workflow versioning

- .github/workflows/pre-release.yml
- Fixes docker build in pre-release workflow (was referring to the wrong action; now refers to the action in keptn/gh-automation repo)
- Fixes gh upload lint tool in pre-release workflow (files were moved into the wrong folder, hence the upload failed)
Fixes #137 and #131
> build: Fix pre-release workflow (#137, #131)

- README.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/k8sutils/job.go
- pkg/k8sutils/job_test.go
Introduce support for specifying imagePullPolicy for tasks in
configuration.
No validation of the value is performed on client side,
we are relying on kubernetes apiserver to perform all the necessary
validations and apply sensible default as specified in
https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
> feat(core): support imagePullPolicy for tasks(#127)

- chart/templates/configmap.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
- cmd/job-executor-service/main.go
- pkg/k8sutils/job.go
- Adds Kubernetes API access to jobs via an environment/helm value
Download helm charts from [CI Build](https://github.com/keptn-contrib/job-executor-service/actions/runs/1637358883) and extract them
Install:
```bash
helm upgrade --install -n keptn job-executor-service job-executor-service-0.1.5-dev-PR-146.tgz --set jobConfig.enableKubernetesApiAccess=true --wait
```
Run a job config that requires Kubernetes API access, e.g.:
> feat(core): Add kubernetes api access to jobs

- .dockerignore
- Dockerfile
- chart/templates/deployment.yaml
- chart/values.schema.json
- initcontainer.Dockerfile
- skaffold.yaml
- enables skaffold to also build and deploy the initcontainer
- added a `rollme` annotation to the deployment of job-executor-service such that it always restarts, even when just helm values are updated (and not the Kubernetes image itself)
- Update `Dockerfile` and `initcontainer.Dockerfile` to look the same
```
skaffold run --tail
```
```
keptn trigger delivery ...
```
> chore: Enable skaffold to build and deploy initcontainer

- chart/values.schema.json
This reverts commit ed463da98fb50b90fa485483f81505bea49855dd.
Still not clear how a '+' character got into the keptn api token.
Needs more investigation about the root cause rather than a quick fix.
Reverting the change till we know more.
Reverts #160
> fix: Revert "Allow '+' in API Token helm value (#160) (#159)"

- cmd/job-executor-service/main.go
Removed code that skipped any event that did not contain '.triggered' in
the type. This will allow the usage of 'silent mode' when matching event
types different from '*.triggered'
> fix: Allow handling of event types other than *.triggered

- docs/MIGRATION-GUIDE-GENERIC-EXECUTOR-SERVICE.md
This PR provides a migration guide in order for generic-executor-service users to easily migrate to job-executor-service
Part of https://github.com/keptn-sandbox/generic-executor-service/issues/16
**Examples**
```console
keptn trigger delivery --project jes --service jes --image=foobar:1.2.3
```
* Bash
```
Job job-executor-service-job-7e0a4918-5786-45ab-99f2-28b6-1 finished successfully!
Logs:
This is my deployment.triggered.sh script
Project = jes
Service = jes
Stage = dev
Image = foobar:1.2.3
DeploymentStrategy = 
TestToken = 1234
hiho
```
* Python
```
Job job-executor-service-job-06832c8f-b6c1-4ef1-ab20-fcc5-1 finished successfully!
Logs:
This is my generic handler script and I got passed  as parameter
I also have some env variables, e.g: …
```
> docs: Added migration guide for generic-executor-service

- README.md
* Updated comaptibility matrix to include the 0.1.8 release
* moved older versions into a collapsible section
[Preview](https://github.com/keptn-contrib/job-executor-service/tree/patch/compatibility-matrix#compatibility-matrix)
> docs: updated compatibility matrix

- skaffold.yaml
Until https://github.com/keptn-contrib/job-executor-service/issues/209 gets implemented, we can leverage this simple change to have an API token set as an environment variable when running skaffold.
See https://skaffold.dev/docs/environment/templating/ for more infos on templating with skaffold.
Example to run:
```bash
KEPTN_API_TOKEN=abcd skaffold run --tail
```
Or even better
```bash
KEPTN_API_TOKEN=$(kubectl get secret keptn-api-token -n keptn -ojsonpath='{.data.keptn-api-token}' | base64 -d) skaffold run --tail
```
> build: Add api-token to skaffold.yaml for better dev experience

- README.md
Installing Job-Executor-Service with Keptn 0.14.x should work, but it requires us to use "remote execution-plane" setup (which is the default in the current master branch).
> docs: Provide incompatibility warning for Keptn 0.14.x

- pkg/eventhandler/eventhandlers.go
- pkg/eventhandler/fake/eventhandlers_mock.go
- pkg/k8sutils/job.go
- pkg/k8sutils/pod.go
- pkg/k8sutils/pod_test.go
* improves the debugging experience by including all logs of all containers in a pod when reporting back the logs (related to #123)
* adds the failure reason and message / exit code of a container to the error log 
* #124
> feat: Include logs of all containers in error message

- chart/README.md
- chart/templates/configmap.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
- cmd/job-executor-service/main.go
- pkg/k8sutils/job.go
- pkg/k8sutils/job_test.go
- test/data/e2e/taskdeadline.config.yaml
- test/e2e/taskdeadline_test.go
- test/events/e2e/taskdeadline.triggered.json
- test/shipyard/e2e/taskdeadline.deployment.yaml
Added a new setting in the helm chart `jobconfig.taskDeadlineSeconds`: if set to a value > 0 jobs exceeding the deadline will be  terminated.
The feature is disabled by default.
> feat: limit job run time

- .github/workflows/integration-tests.yaml
> test: remove bash tracing in wait for k3s readiness in integration tests

- chart/Chart.yaml
Set helm chart version to 0.0.0-dev (was 0.1.4 before).
This helps when deploying the chart using skaffold.
Note: The actual version is set as part of the build-helm-chart workflow:
> chore: set helm chart version to 0.0.0-dev

- chart/templates/serviceaccount.yaml
- pkg/eventhandler/eventhandlers.go
- pkg/eventhandler/fake/eventhandlers_mock.go
- pkg/k8sutils/job.go
- pkg/k8sutils/job_test.go
Disclaimer: Thanks to the code provided by @Raffy23 in PR https://github.com/keptn-contrib/job-executor-service/pull/229
Fixes #234 by providing an appropriate error message
Unfortunately, we cannot easily fix #235, as it would require us to delete jobs (which we shouldn't do at the moment). I would dedicate the fix of #235 to the refactoring ticket of #244
> fix: Add output of failed events to logs

- .github/workflows/integration-tests.yaml
FYI @pchila 
This should fix the failing integration tests / being unable to fetch logs. I also removed continue-on-error.
> test: Get logs for integration tests from deployment rather than by pod/label

- README.md
- docs/INSTALL.md
- updates the JES version in the installation docs to 0.2.3
> docs: Update JES version in installation docs

- .github/actions/github-script/fetch_keptn_versions.sh
- .github/workflows/integration-tests.yaml
- Fetches the latest Keptn release and prerelease
- Adds the versions to the Github action matrix
- Checks if the Keptn chart is available in the default Helm repository (`https://charts.keptn.sh`). If not, `https://charts-dev.keptn.sh` is used instead.
Integration Tests: https://github.com/keptn-contrib/job-executor-service/actions/runs/2649231941
> feat: Add Keptn dev version to integration tests

- .github/workflows/integration-tests.yaml
With PR #314 we are now testing against newer Keptn version (latest release and latest pre-release). However, it seems that we're not compatible.
This PR updates pipeline code to be compatible with Keptn 0.17 (note: this only proves that we're compatible with Keptn 0.17, we haven't put any effort into making it compatible, e.g., using a new distributor version).
I also slimmed down and updated the test matrix for Keptn versions, e.g.:
* Removed 0.13.x (we have plenty of 0.13 compatible releases that people can use)
* Removed 0.14.x (we have plenty of 0.14 compatible releases that people can use)
* Keep 0.15.1
* Update from 0.16.0 to 0.16.1
Integration Test Run: https://github.com/keptn-contrib/job-executor-service/actions/runs/2703312389
> chore: Update pipeline to be compatible with Keptn 0.17

- .github/workflows/integration-tests.yaml
- includes previous containers in logs to make it easier to debug if a service crashes
> chore: Improve integration tests log output

- pkg/keptn/errorlog.go
- pkg/keptn/errorlog_test.go
- changes sending error logs to Keptn uniform to all registered jes instances
> fix: Sending error logs to all registered jes instances in uniform

- CHANGELOG.md
- docs/INSTALL.md
* Added special note about protocol as we changed the default value.
* Manually synced changelog from releases
* Updated install and upgrade instructions
Preview: 
* [CHANGELOD.md](https://github.com/keptn-contrib/job-executor-service/blob/patch/remotecontrolplane-protocol/CHANGELOG.md)
* [INSTALL.md](https://github.com/keptn-contrib/job-executor-service/blob/patch/remotecontrolplane-protocol/docs/INSTALL.md)
> docs: Improve upgrade guide and breaking change documentation

- .github/workflows/integration-tests.yaml
- README.md
- chart/templates/deployment.yaml
- chart/values.yaml
* Upgrade keptn/distributor to 0.17.0
* Set `API_PROXY_MAX_PAYLOAD_BYTES_KB` to 64 (kilobytes) to allow large logs to be transmitted via distributor
* Update integration test matrix
Integration Test: https://github.com/keptn-contrib/job-executor-service/actions/runs/2826043359
> feat: Keptn 0.17 compatibility
