- README.md
- go.mod
- go.sum
- releasenotes/releasenotes_V0.1.3.md
* Added table of contents to readme
* Release notes
Compatible with Keptn 0.8.4
* Allow array of strings for command, add args that are also passed through to the kubernetes job (#31)
* Provide a cli tool that validates job configurations (#33)
* Support env variables from string (#34, #36)
* Allow setting the working directory of a kubernetes job (#38)
* Fix kubernetes labels used by distributor for uniform registration (#32)
* Uniform registration for remote execution planes over https doesn't work (https://github.com/keptn/keptn/issues/4516)
> Release 0.1.3

- cmd/job-executor-service/main.go
- pkg/eventhandler/eventhandlers.go
- pkg/k8sutils/job.go
Signed-off-by: Thomas Schuetz <thomas.schuetz@dynatrace.com>
> implemented AlwaysSendFinishedEvent

- pkg/eventhandler/eventhandlers.go
Signed-off-by: Thomas Schuetz <thomas.schuetz@dynatrace.com>
> add .started event when always send finished event

- pkg/k8sutils/job.go
- pkg/k8sutils/job_test.go
* Fix issue with yaml formatting, was currently ignored if parsed jsonpath resulted in a map.
* Extend test with env for default json formatting and yaml formatting
> Add test for json and yaml env formatting

- README.md
Documentation for the feature implemented in https://github.com/keptn-sandbox/job-executor-service/pull/67
> Add readme for namespace feature

- helm/templates/configmap.yaml
- helm/templates/deployment.yaml
- helm/templates/serviceaccount.yaml
- releasenotes/releasenotes_V0.1.5.md
Signed-off-by: jetzlstorfer <juergen.etzlstorfer@dynatrace.com>
> make serviceaccount creation optional

- .github/workflows/validate-semantic-pr.yml
- Adds semantic PR check (requires PR title to be set correctly; if only one commit, it requires the commit message to be set correctly)
> chore: Added semantic PR check

- CODEOWNERS
I am hereby requesting to become a CODEOWNER of this service.
> chore: add christian-kreuzberger-dtx as a codeowner

- CODEOWNERS
- Adds @TannerGabriel , @TannerGilbert and @Paolo-Chila as Codeowners
> chore: Add Gilbert Tanner, Gabriel Tanner and Paolo Chila as Codeowners

- README.md
- pkg/config/config_test.go
- pkg/k8sutils/job_test.go
> docs:  Document ttlSecondsAfterFinished (#126)

- README.md
- Adds docs for remote execution plane docs
Fixes #151
> docs: Added docs regarding remote execution plane (#151)

- README.md
- pkg/eventhandler/eventhandlers.go
- pkg/k8sutils/connect.go
- pkg/k8sutils/fake/connect_mock.go
- pkg/k8sutils/job.go
> fix: clean-up pods when deleting kubernetes jobs (#154)

- chart/values.schema.json
Signed-off-by: Adam Gardner <adam.gardner@dynatrace.com>
> fix(#159) Fix API Token Regex

- README.md
Update README with new keptn version compatibility
> chore: prepare release 0.1.7

- go.mod
- go.sum
Update keptn/kubernetes-utils to v0.12
> build: update keptn/kubernetes-utils to v0.12

- go.mod
- go.sum
- pkg/config/config_test.go
- pkg/eventhandler/eventhandler_test.go
- pkg/file/file_test.go
- pkg/k8sutils/resourcerequirements_test.go
- pkg/keptn/config_service_test.go
> test: use stretchr/testify for assertions

- pkg/k8sutils/job.go
> feat: Use pullPolicy ifNotPresent for initContainer

- chart/templates/deployment.yaml
- cmd/job-executor-service/main.go
Implement liveness and readiness endpoints and use them in Helm files.
#174
> feat: Implement liveness and readiness endpoints

- .github/actions/unit-tests/action.yml
Run unit test collecting and formatting output using gotestsum.
Publish the report of unit test runs in pull requests as a comment.
> build: add gotestsum for better unit tests output

- FEATURES.md
- README.md
- moves a leftover paragraph regarding `ttlSecondsAfterFinished` from README to FEATURE
- adds guidance on how to change certain helm values (e.g., API Token) using `helm upgrade`
> docs: Add guidance for updating api-token, topic subscription to README

- chart/values.yaml
- skaffold.yaml
Upgrading keptn/distributor to 0.12.6
> build: Upgrade keptn/distributor to 0.12.6

- FEATURES.md
Signed-off-by: Thomas Schuetz <thomas.schuetz@dynatrace.com>
> docs: fixed documentation for the usage of labels

- skaffold.yaml
> build: update skaffold configuration to allow debugging

- FEATURES.md
- chart/README.md
- chart/templates/configmap.yaml
- chart/templates/deployment.yaml
- chart/templates/jobserviceaccount.yaml
- chart/values.yaml
- cmd/job-executor-service/main.go
- pkg/config/config.go
- pkg/k8sutils/job.go
* introduces service accounts for the job workload tasks
* removes the `enableKubernetesApiAccess` flag from JES
* #144
> feat!: Introduce serviceAccount for job workloads

- go.mod
- go.sum
- test/e2e/utils.go
- removes the prometheus log dependency from JES
> refactor: remove prometheus dependency

- README.md
- chart/README.md
- chart/templates/_helpers.tpl
- chart/templates/configmap.yaml
- chart/templates/tests/test-api-connection.yaml
- chart/values.schema.json
- chart/values.yaml
- skaffold.yaml
- Adds an auto-detection flag to the JES installation that is able to detect a single Keptn instance and extract the API token from it
- #209
> feat: Add Keptn auto-detection

- .github/workflows/integration-tests.yaml
- Adds more output for the pipeline integration tests
> feat: Add output to go test in pipeline

- .github/workflows/integration-tests.yaml
Update Keptn versions in integration tests
* Add 0.15.0
* Remove: 0.11.x
* Change: 0.14.1 -> 0.14.2
* Change: 0.13.4 -> 0.13.5
* Change: 0.12.6 -> 0.12.7
Integration Tests: https://github.com/keptn-contrib/job-executor-service/actions/runs/2318038954
| Test                                                         |       0.12.7       |       0.13.5       |       0.14.2       |       0.15.0       |
| :----------------------------------------------------------- | :----------------: | :----------------: | :----------------: | :----------------: |
| TestEnvironmentVariables                                     | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| TestResourceFiles                                            | :heavy_check_mark: | …
> chore: Update Keptn versions in integration tests

- chart/README.md
- chart/templates/configmap.yaml
- chart/templates/deployment.yaml
- chart/values.yaml
- cmd/job-executor-service/main.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/reader.go
- pkg/config/reader_test.go
- pkg/eventhandler/eventhandlers.go
- pkg/eventhandler/eventhandlers_test.go
- pkg/eventhandler/fake/eventhandlers_mock.go
- pkg/k8sutils/job.go
- pkg/k8sutils/job_test.go
- pkg/utils/labels.go
- pkg/utils/labels_test.go
- test/data/invalid-user-defined-labels.yaml
- test/data/user-defined-labels.yaml
- test/events/test.triggered.with-gitcommitid.json
* adds generated and user defined labels to Kubernetes jobs
> feat: Add job labels

- chart/templates/_helpers.tpl
- chart/templates/configmap.yaml
- chart/templates/deployment.yaml
- chart/templates/secrets.yaml
- chart/values.schema.json
- chart/values.yaml
- cmd/job-executor-service-initcontainer/main.go
- pkg/k8sutils/job.go
- skaffold.yaml
- test/e2e/envvar_test.go
- test/e2e/keptn.go
- test/e2e/utils.go
* adds OAuth to the job executor service
* adds OAuth to the ini-containers
> feat: OAuth authentication mode

- docs/INSTALL.md
* adds installation instructions for OAuth
> docs: Add OAuth installation instructions

- chart/templates/networkpolicy.yaml
> fix: fix typo in network policy helm template

- CHANGELOG.md
Signed-off-by: Raphael Ludwig <raphael.ludwig@dynatrace.com>
Co-authored-by: GitHub Actions <actions@github.com>
> build(release): 0.2.1 (#283)

- .github/workflows/integration-tests.yaml
- fixes the naming of the debug archives in the integration tests
> fix: Integration tests debug archive

- docs/FEATURES.md
- docs/NETWORK-POLICIES.md
> docs: document ingress/egress job-executor-services network policies

- .github/workflows/integration-tests.yaml
- chart/values.schema.json
Switch to [action-install-keptn v2](https://github.com/keptn-sandbox/action-install-keptn/tree/v2.0.0).
Remove dependencies on Keptn CLI.
> ci: use new keptn install action

- docs/FEATURES.md
- pkg/config/config.go
- pkg/k8sutils/job.go
- pkg/k8sutils/job_test.go
- Adds functionality to specify annotations for your Job
- Documents changes in `docs/features`
> feat: Ability to specify annotations for jobs

- .github/workflows/integration-tests.yaml
- pkg/file/file.go
- pkg/keptn/config_service.go
- pkg/keptn/config_service_test.go
- test/data/e2e/folder.config.yaml
- test/e2e/files_test.go
- test/events/e2e/folder.triggered.json
- test/shipyard/e2e/folder.deployment.yaml
- fixes the way of how directories are handled in the init container
> fix: Handling of directories in the init container 

- .github/workflows/integration-tests.yaml
This adds a summary to the integration test run
https://github.com/keptn-contrib/job-executor-service/actions/runs/2636182635
> feat: Post integration test summary to GH workflow

- chart/values.yaml
Update keptn/distributor to 0.16.1
> build(deps): Update keptn/distributor to 0.16.1

- README.md
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>
> docs: Update compatibility matrix

- test/data/e2e/jobconfig.project.config.yaml
- test/data/e2e/jobconfig.service-1.config.yaml
- test/data/e2e/jobconfig.stage-dev.config.yaml
- test/e2e/jobconfig_test.go
- test/events/e2e/jobconfig.dev-1.triggered.json
- test/events/e2e/jobconfig.dev-2.triggered.json
- test/events/e2e/jobconfig.prod.triggered.json
- test/shipyard/e2e/jobconfig.deployment.yaml
- Adds integration tests for the global configuration that was introduced with #145
> test: Add integration tests for global configuration

- .github/actions/unit-tests/action.yml
- .github/workflows/integration-tests.yaml
- .github/workflows/reviewdog.yml
- Dockerfile
- go.mod
- updates JES to Go 1.18
- fixes reviewdog action
> chore: Update to Go 1.18
